# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamiko', '0002_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormessage',
            name='visitor_phone',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
