# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamiko', '0005_visitormessage_visitor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='item name', max_length=500)),
                ('description_one', models.TextField(blank=True, help_text='What it is. For what. What are the materials.', max_length=5000, null=True)),
                ('description_two', models.TextField(blank=True, help_text='Dimensions. Production time.', max_length=5000, null=True)),
                ('price', models.IntegerField(help_text='Price')),
                ('detail_description_one', models.TextField(blank=True, help_text='other description #1', max_length=5000, null=True)),
                ('detail_description_two', models.TextField(blank=True, help_text='other description #2', max_length=5000, null=True)),
                ('title', models.CharField(help_text='title page', max_length=500)),
                ('meta_description', models.CharField(help_text='meta description', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
