# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamiko', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_one',
            field=models.ImageField(default=None, upload_to='vamiko/items_image'),
        ),
    ]
