# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamiko', '0007_item_image_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_four',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_tree',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_two',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_one',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
