# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamiko', '0008_auto_20160403_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_four',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_tree',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_two',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
