# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vamiko', '0009_auto_20160403_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url_item_name',
            field=models.CharField(blank=True, help_text='item url name. latin symbols!', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_four',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_one',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_tree',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_two',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
