django:
  image: muroslav/vamiko
  #build: .
  command: "sh deploy.sh"
  environment:
    RUN_ENV: "$RUN_ENV"
  ports:
   - "80:8001"
  volumes:
   - .:/project
  links:
   - redis
redis:
  image: redis:latest
  command: redis-server --appendonly yes