# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecheckerbase',
            name='free_date',
            field=models.DateTimeField(null=True),
        ),
    ]
